name: Shelf-Genie Deployment on Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build-and-Push-on-ACR:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Install Requirements
        run: |
          pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      - name: Run Pipeline
        run: python demo.py

      - name: Build and Push Docker Image on ACR
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/recommendation-system-api .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/recommendation-system-api

  Deploy-on-Azure:
    needs: Build-and-Push-on-ACR
    runs-on: self-hosted  
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}

    steps:
      - name: Login to Azure Container Registry on VM
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Set up SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_KEY }}
          script: |
            echo "🛑 Stopping any existing container"
            if [ "$(docker ps -q -f name=shelfgenie-api)" ]; then
              docker stop shelfgenie-api
              docker rm shelfgenie-api
            fi

            echo "⬇️ Pulling latest Docker image"
            docker pull ${{ secrets.ACR_LOGIN_SERVER }}/recommendation-system-api

            echo "🚀 Starting new container"
            docker run -d --name shelfgenie-api -p 5000:5000 -e AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" ${{ secrets.ACR_LOGIN_SERVER }}/recommendation-system-api

